name: FE-BPay CI/CD Test
on:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.18.0

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Package
        run: yarn install

      - name: Build
        run: yarn build
        env:
          CI: false
